---

env:
  RUNLEVEL: 1

nginx_max_clients: 768

nginx_http_params:
  sendfile: "off"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: 65
  types_hash_max_size: 2048
  access_log: "/var/log/nginx/access.log"
  error_log: "/var/log/nginx/error.log"

nginx_sites:
  #  - server:
  #    server_name: "test.kwantera.com"
  #    file_name: "test.kwantera.com"
  #    listen: 80
  #    return: "301 https://murphy.kwantera.com$request_uri"

  - server:
      file_name: "test.eventgine.co"
      configuration:
        server_name: "test.eventgine.co"
        listen: 80
        # listen: 443
        # ssl: "on"
        # ssl_certificate: "path/to/somecert.cert"
        # ssl_certificate_key: "path/to/key/somekey.key"
        access_log: "/var/log/nginx/eg.access.log"
        error_log: "/var/log/nginx/eg.error.log"
        location:
            - name: "/"
              configuration:
                try_files: "$uri /index.html =500"
                root: "/home/ubuntu/src/eventgine-static/"

  - server:
      file_name: "test.api.eventgine.co"
      configuration:
        server_name: "test.api.eventgine.co"
        listen: 80
        # listen: 443
        # ssl: "on"
        # ssl_certificate: "path/to/somecert.cert"
        # ssl_certificate_key: "path/to/key/somekey.key"
        access_log: "/var/log/nginx/api.eg.access.log"
        error_log: "/var/log/nginx/api.eg.error.log"
        location:
          - name: "/"
            configuration:
              try_files: "$uri @eg"
              root: "/home/ubuntu/src/eventgine/"
              if:
                - name: "($request_method = OPTIONS)"
                  configuration:
                    add_header:
                      - "Content-Length 0"
                      - "Content-Type text/plain"
                      - "Access-Control-Allow-Origin *"
                      - "Access-Control-Allow-Methods \"GET,OPTIONS,HEAD,PUT,POST,DELETE,PATCH\""
                      - "Access-Control-Allow-Headers \"origin, x-http-method-override, accept, content-type, authorization, x-pingother, if-match, if-modified-since, if-none-match, if-unmodified-since, x-requested-with\""
                      - "Access-Control-Expose-Headers \"tag, link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes\""
                    return: "200"
          - name: "@eg"
            configuration:
              proxy_pass: "http://localhost:8000"
              proxy_set_header:
                - "Host $host"
                - "X-Real-IP $remote_addr"
                - "X-Forwarded-For $proxy_add_x_forwarded_for"



