---

env:
  RUNLEVEL: 1

nginx_max_clients: 768

nginx_http_params:
  sendfile: "on"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: 65
  types_hash_max_size: 2048
  access_log: "/var/log/nginx/access.log"
  error_log: "/var/log/nginx/error.log"

nginx_sites:
#  - server:
#    server_name: "test.kwantera.com"
#    file_name: "test.kwantera.com"
#    listen: 80
#    return: "301 https://murphy.kwantera.com$request_uri"

  - server:
      server_name: "test.eventgine.co"
      file_name: "test.eventgine.co"
      listen: 80
#     listen: 443
#     ssl: "on"
#     ssl_certificate: "path/to/somecert.cert"
#     ssl_certificate_key: "path/to/key/somekey.key"
      access_log: "/var/log/nginx/eg.access.log"
      error_log: "/var/log/nginx/eg.error.log"
      location1: {name: "/", try_files: "$uri @eg"}
      location2: {name: "@eg", proxy_pass: "localhost:8000", proxy_set_header: 'Host $host', proxy_set_header: "X-Forwarded-For", proxy_set_header: "X-Real-IP $remote_addr", proxy_set_header: "X-Forwarded-For $proxy_add_x_forwarded_for"}
      location3: {name: "/static", alias: "/home/ubuntu/src/static"}
